[sandbox_workspace_write]
network_access = true

[mcp_servers.notion]
url = "https://mcp.notion.com/mcp"

[mcp_servers.figma]
url = "https://mcp.figma.com/mcp"

[mcp_servers.linear]
url = "https://mcp.linear.app/mcp"

[mcp_servers.rememberthemilk]
url = "https://www.rememberthemilk.com/mcp"

[plugins."google-calendar@openai-curated"]
enabled = true

[plugins."figma@openai-curated"]
enabled = true

[plugins."github@openai-curated"]
enabled = true
