"" 表示
" 文字コード
set encoding=utf-8
" インデント
set autoindent
set smartindent
" 行番号の表示
set number
" 編集中の行をハイライト
set cursorline
" 対応する括弧をハイライト
set showmatch
set matchtime=1
" インクリメンタルサーチを有効にする
set incsearch
" 編集中のファイルでも保存せず他のファイルを表示する
set hidden
" タブを空白文字に置き換える
set expandtab
" タブサイズ
set tabstop=2
set shiftwidth=2 
" others
set backspace=indent,eol,start

"" ステータス行
" ステータス行を常に表示
set laststatus=2
" ファイル名表示
set statusline=%F
" 変更チェック表示
set statusline+=%m
" これ以降は右寄せ表示
set statusline+=%=
" ステータスラインにbranchを表示
set statusline+=%{fugitive#statusline()}
" 空白2つ挿入
set statusline+=\ \ 
" カーソル行の表示
set statusline+=%1l/%L

"" バックアップ
" backupファイルを作成しない
set nobackup
" swapファイルを作成しない
set noswapfile

"" Plugin
call plug#begin('~/.vim/plugged')
Plug 'tpope/vim-fugitive'
Plug 'scrooloose/nerdtree'
Plug 'itchyny/lightline.vim'
Plug 'cocopon/iceberg.vim'
call plug#end()

colorscheme iceberg

filetype plugin indent on
syntax enable

" move window
nnoremap sl <C-w>l
nnoremap sh <C-w>h
nnoremap sL <C-w>L
nnoremap sH <C-w>H

" move cursor
nnoremap H ^
nnoremap L $

" ノーマルモード時だけ ; と : を入れ替える
nnoremap ; :
nnoremap : ;

" filetype毎のインデントの設定
if has("autocmd")
  filetype plugin on
  filetype indent on
  autocmd FileType ruby setlocal sw=2 sts=2 ts=2 et
end

" NOTE: どこかで上書きされるので最後に記述
set shortmess-=S
