- name: update homebrew
  homebrew:
    update_homebrew: yes

- name: install cask apps
  community.general.homebrew_cask:
    name:  "{{ homebrew.applications }}"
    state: present
    accept_external_apps: yes
  when: (homebrew.applications | default([]) | length) > 0

- name: tap repositories
  community.general.homebrew_tap:
    name:  "{{ homebrew.tap_repositories }}"
    state: present
  when: (homebrew.tap_repositories | default([]) | length) > 0

- name: install homebrew packages
  homebrew:
    name: "{{ homebrew.packages }}"
    state: present
  when: (homebrew.packages | default([]) | length) > 0
