- name: create parent dirs
  file:
    dest:    '{{ home_path }}/{{ item.dest | dirname }}'
    state:   directory
    recurse: yes
  when: (item.dest | dirname) != ""
  loop: '{{ links | default([]) }}'

- name: create symlinks
  file:
    src:   '{{ dotfiles_path }}/{{ item.src }}'
    dest:  '{{ home_path }}/{{ item.dest }}'
    state: link
  loop: '{{ links | default([]) }}'

- name: copy files
  copy:
    src:   '{{ dotfiles_path }}/{{ item.key }}'
    dest:  '{{ home_path }}/{{ item.value }}'
  with_dict: '{{ copy }}'
