homebrew:
  applications:
    - alacritty
    - alfred
    - android-studio
    - clipy
    - docker
    - figma
    - google-chrome
    - google-cloud-sdk
    - kindle
    - notion
    - slack
    - typora
    - visual-studio-code
  packages:
    - ag
    - autoconf
    - coreutils
    - direnv
    - fswatch
    - fzf
    - git
    - go
    - gpg
    - hub
    - jq
    - kubectl
    - kustomize
    - minikube
    - mysql@5.7
    - openssl
    - terragrunt
    - tig
    - tree
    - tmux
    - packer
    - peco
    - yamllint

asdf:
  dir: '{{ home_path }}/.asdf'
  version: v0.8.0
  plugins:
    - ruby
    - elixir
    - erlang
    - nodejs
    - python
    - terraform
    - golang
  global_settings:
    golang: 1.19.3

go:
  packages:
    - github.com/x-motemen/ghq
    - golang.org/x/tools/cmd/goimports

link:
  zsh/zshrc: .zshrc
  vim/vimrc: .vimrc
  git/gitconfig: .gitconfig
  git/gitignore: .gitignore
  git/git_template: .git_template
  tmux/tmux.conf: .tmux.conf
  alacritty.yml: .config/alacritty/alacritty.yml

vim:
  dir: '{{ home_path }}/vim'

vscode:
  extensions:
    - MS-CEINTL.vscode-language-pack-ja
    - cocopon.iceberg-theme
