homebrew:
  applications:
    - alacritty
    - alfred
    - docker
    - google-chrome
    - google-cloud-sdk
    - notion
    - slack
    - typora
  packages:
    - ag
    - autoconf
    - coreutils
    - direnv
    - fswatch
    - fzf
    - git
    - go
    - gpg
    - hub
    - jq
    - kubectl
    - kustomize
    - minikube
    - mysql@5.7
    - tig
    - tree
    - tmux
    - packer
    - peco
    - yamllint

asdf:
  dir:     '{{ home_path }}/.asdf'
  version: v0.8.0
  plugins:
    - ruby
    - elixir
    - erlang
    - nodejs
    - python
    - terraform

go:
  packages:
    - github.com/x-motemen/ghq
    - golang.org/x/tools/cmd/goimports

link:
  zsh/zshrc: .zshrc
  vim/vimrc: .vimrc
  git/gitconfig: .gitconfig
  git/gitignore: .gitignore
  git/git_template: .git_template
  tmux/tmux.conf: .tmux.conf
  alacritty.yml: .config/alacritty/alacritty.yml

vim:
  dir: '{{ home_path }}/vim'
