homebrew:
  applications:
    - alacritty
    - alfred
    - android-studio
    - background-music
    - claude
    - clipy
    - cursor
    - docker
    - figma
    - google-chrome
    - google-cloud-sdk
    - google-japanese-ime
    - notion
    - obsidian
    - remember-the-milk
    - slack
    - typora
    - visual-studio-code
  tap_repositories:
    - dbt-labs/dbt
  packages:
    - ag
    - autoconf
    - cocoapods
    - coreutils
    - dbt-bigquery
    - direnv
    - fswatch
    - fzf
    - gh
    - git
    - go
    - gpg
    - hub
    - java
    - jq
    - kubectl
    - kustomize
    - minikube
    - mysql@5.7
    - node
    - openssl
    - terragrunt
    - tig
    - tree
    - tmux
    - packer
    - peco
    - yamllint

asdf:
  dir: '{{ home_path }}/.asdf'
  version: v0.8.0
  plugins:
    - ruby
    - elixir
    - erlang
    - nodejs
    - python
    - terraform
    - golang
  global_settings:
    golang: 1.19.3
    nodejs: 23.10.0

go:
  packages:
    - github.com/x-motemen/ghq@latest
    - golang.org/x/tools/cmd/goimports@latest
    - golang.org/x/tools/gopls@latest
    - github.com/ramya-rao-a/go-outline@latest
    - github.com/766b/go-outliner@latest
    - github.com/go-delve/delve/cmd/dlv@latest
    - github.com/davidrjenni/reftools/cmd/fillstruct@latest
    - github.com/cweill/gotests/gotests@v1.6.0
    - honnef.co/go/tools/cmd/staticcheck@2022.1
    - github.com/hhatto/gocloc/cmd/gocloc@latest
    - github.com/fzipp/gocyclo/cmd/gocyclo@latest

npm:
  packages:
    - "@abhiz123/todoist-mcp-server"
    - "@ubie-oss/slack-mcp-server"
    - "@anthropic-ai/claude-code"

link:
  asdf/asdfrc: .asdfrc
  zsh/zshrc: .zshrc
  vim/vimrc: .vimrc
  git/gitconfig: .gitconfig
  git/gitignore: .gitignore
  git/git_template: .git_template
  npm/npmrc: .npmrc
  tmux/tmux.conf: .tmux.conf
  alacritty.yml: .config/alacritty/alacritty.yml

vim:
  dir: '{{ home_path }}/vim'

vscode:
  extensions:
    # base
    - MS-CEINTL.vscode-language-pack-ja
    - alefragnani.project-manager
    - vscodevim.vim
    - MS-vsliveshare.vsliveshare
    - inu1255.easy-snippet
    - eamodio.gitlens
    # color
    - cocopon.iceberg-theme
    # go
    - golang.Go
    - 766b.go-outliner
    - windmilleng.vscode-go-autotest
    # flutter
    - Dart-Code.flutter
    # swagger
    - Arjun.swagger-viewer
    # terraform
    - HashiCorp.terraform
    # docker
    - ms-azuretools.vscode-docker
    # makefile
    - ms-vscode.makefile-tools
    # TypeScript
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
    # perl
    - kraih.mojolicious
