homebrew:
  applications:
    - alacritty
    - alfred
    - docker
    - google-chrome
    - google-cloud-sdk
    - notion
    - slack
  packages:
    - ag
    - autoconf
    - coreutils
    - direnv
    - fswatch
    - fzf
    - git
    - go
    - gpg
    - hub
    - jq
    - kustomize
    - mysql@5.7
    - tig
    - tmux
    - peco

asdf:
  dir:     '{{ home_path }}/.asdf'
  version: v0.8.0
  plugins:
    - ruby
    - elixir
    - erlang
    - nodejs

go:
  packages:
    - github.com/x-motemen/ghq

link:
  zsh/zshrc: .zshrc
  vim/vimrc: .vimrc
  git/gitconfig: .gitconfig
  git/git_template: .git_template
  tmux/tmux.conf: .tmux.conf
  alacritty.yml: .config/alacritty/alacritty.yml

vim:
  dir: '{{ home_path }}/vim'
